version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell
    - gocyclo
  settings:
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    paths:
      - bin
      - dist
formatters:
  enable:
    - gofmt
